export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  telegramPublicSearchBaseUrl: process.env.TELEGRAM_PUBLIC_SEARCH_BASE_URL?.replace(/\/$/, "") ?? "",
  telegramPublicSearchApiKey: process.env.TELEGRAM_PUBLIC_SEARCH_API_KEY ?? "",
  telegramTdlibSearchBaseUrl: process.env.TELEGRAM_TDLIB_SEARCH_BASE_URL?.replace(/\/$/, "") ?? "",
  telegramTdlibSearchApiKey: process.env.TELEGRAM_TDLIB_SEARCH_API_KEY ?? "",
  telegramDirectoryBaseUrl: process.env.TELEGRAM_DIRECTORY_BASE_URL?.replace(/\/$/, "") ?? "",
  telegramDirectoryApiKey: process.env.TELEGRAM_DIRECTORY_API_KEY ?? "",
};
